# [START django_app]
runtime: python37
env_variables:
  DJANGO_SETTINGS_MODULE: travelfootprint.settings_prod

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: auto
  secure: always

# [END django_app]
